spring:
  application:
    name: mcp
  main:
    banner-mode:
      off
  web-application-type:
    none

  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        name: shah-mcp
        version: 0.0.1
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
        type: sync
        capabilities:
          completion: true
          prompt: true
          resource: true
          tool: true

logging:
  pattern:
    console:
  file:
    name: /Users/shah/Documents/projects/spring-ai/mcp/logs/mcp-stdio-server.log
